const navLinks: NavLink[] = [
    {
        id: 1,
        name: "Home",
        link: "/",
    },
    {
        id: 2,
        name: "4K",
        link: "/4K",
    },
    {
        id: 3,
        name: "Trending",
        link: "/trending",
    },
    {
        id: 4,
        name: "Browse Movies",
        link: "/browse-movies",
    }
];

const dropdownlist: DropdownList[] =[
    {
        id: '1',
        name: "Quality",
        options: [
            'All',
            '480p',
            '720p',
            '1080p',
            '1080p.x265',
            '2160p',
            '3D'
        ]
    },
    {
        id: '2',
        name: "Genre",
        options: [
            'All',
            'Action',
            'Adventure',
            'Animation',
            'Biography',
            'Comedy',
            'Crime',
            'Documentary',
            'Drama',
            'Family',
            'Fantasy',
            'Film-Noir',
            'Game-Show',
            'History',
            'Horror',
            'Music',
            'Musical',
            'Mystery',
            'News',
            'Reality-TV',
            'Romance',
            'Sci-Fi',
            'Sport',
            'Talk-Show',
            'Thriller',
            'War',
            'Western'
            ]
    },
    {
        id: '3',
        name: "Ratings",
        options: [
            'All',
            '9+',
            '8+',
            '7+',
            '6+',
            '5+',
            '4+',
            '3+',
            '2+',
            '1+'
            ]
    },
    {
        id: '4',
        name: "Year",
        options: [
            'All',
            '2024',
            '2023',
            '2020-now',
            '2010-now',
            '2010-2019',
            '2000-2009',
            '1990-1999',
            '1980-1989',
            '1970-1979',
            '1950-1969',
            '1900-1949'
            ]
    },
    {
        id: '5',
        name: "Language",
        options: [
            'English',
            'Foreign',
            'All',
            'French (2917)',
            'Japanese (2597)',
            'Spanish (1598)',
            'Italian (1390)',
            'German (1128)',
            'Chinese (990)',
            'Korean (869)',
            'Cantonese (766)',
            'Hindi (695)',
            'Swedish (407)',
            'Russian (390)',
            'Portuguese (384)',
            'Romanian (340)',
            'Polish (333)',
            'Dutch (241)',
            'Thai (224)',
            'Turkish (218)',
            'Danish (215)',
            'Arabic (151)',
            'Norwegian (150)',
            'Tamil (149)',
            'Indonesian (146)',
            'Finnish (132)',
            'Telugu (126)',
            'Hungarian (125)',
            'Vietnamese (124)',
            'Czech (115)',
            'Tagalog (93)',
            'Persian (88)',
            'Estonian (61)',
            'Ukrainian (58)',
            'Greek (54)',
            'Hebrew (51)',
            'Malayalam (50)',
            'Punjabi (48)',
            'Malay (34)',
            'Bangla (30)',
            'Catalan (26)',
            'Icelandic (22)',
            'Urdu (20)',
            'Slovak (19)',
            'Serbian (19)',
            'Kannada (19)',
            'Marathi (15)',
            'Latvian (13)',
            'Lithuanian (13)',
            'xx (12)',
            'Georgian (10)',
            'Croatian (10)',
            'Bulgarian (10)',
            'Galician (9)',
            'Basque (8)',
            'Serbo-Croatian (8)',
            'Macedonian (7)',
            'Kurdish (7)',
            'Afrikaans (6)',
            'Bosnian (6)',
            'Irish (6)',
            'Wolof (6)',
            'Yoruba (6)',
            'Swahili (5)',
            'Tibetan (5)',
            'Kazakh (5)',
            'Albanian (5)',
            'Amharic (4)',
            'Armenian (4)',
            'Zulu (4)',
            'Slovenian (4)',
            'Cantonese (4)',
            'Khmer (3)',
            'Latin (3)',
            'Pashto (3)',
            'Southern Sotho (3)',
            'Xhosa (3)',
            'Gujarati (3)',
            'Abkhazian (2)',
            'Mongolian (2)',
            'Norwegian Bokmål (2)',
            'Ossetic (2)',
            'Yiddish (2)',
            'Maori (2)',
            'Akan (2)',
            'Haitian Creole (2)',
            'Maltese (2)',
            'cmn (2)',
            'Burmese (2)',
            'Nepali (2)',
            'Lao (2)',
            'Bambara (2)',
            'Dzongkha (2)',
            'Afar (1)',
            'Luxembourgish (1)',
            'Kyrgyz (1)',
            'Azerbaijani (1)',
            'Somali (1)',
            'Inuktitut (1)',
            'Ganda (1)',
            'Belarusian (1)',
            'Igbo (1)',
            'Welsh (1)',
            'No linguistic content (1)',
            'Filipino (1)',
            'Twi (1)',
            'Kinyarwanda (1)',
            'Odia (1)',
            'American Sign Language (1)',
            'Min Nan Chinese (1)',
            'ber (1)',
            'qag (1)',
            'Swiss German (1)',
            'Lingala (1)',
            'Iban (1)',
            'Cree (1)',
            'Javanese (1)',
            'Tswana (1)',
            'qab (1)',
            'Romany (1)',
            'Romanian (1)',
            'Sanskrit (1)',
            'ukl (1)',
            'Uyghur (1)',
            'kvk (1)',
            'Northern Sami (1)',
            'Oromo (1)',
            'myn (1)'
            ]
    },
    {
        id: '6',
        name: "Order By",
        options: [
            'Latest',
            'Oldest',
            'Featured',
            'Seeds',
            'Peers',
            'Year',
            'IMDb Rating',
            'YTS Likes',
            'RT Audience',
            'Alphabetical',
            'Downloads'
            ]
    },

];
const footerLinks: NavLink[]=[
    {
        id: 1,
        name: "Blog",
        link: "https://yts.mx/blog",
    },
    {
        id: 2,
        name: "DMCA",
        link: "https://yts.mx/dmca",
    },
    {
        id: 3,
        name: "API",
        link: "https://yts.mx/api",
    },
    {
        id: 4,
        name: "RSS",
        link: "https://yts.mx/rss-guide",
    },
    {
        id: 5,
        name: "Contact",
        link: "https://yts.mx/contact",
    },
    {
        id: 6,
        name: "Browse Movies",
        link: "https://yts.mx/browse-movies",
    },
    {
        id: 7,
        name: "Requests",
        link: "https://yts.mx/requests",
    },
    {
        id: 8,
        name: "Login",
        link: "https://yts.mx/login",
    },
    {
        id: 9,
        name: "Language",
        link: "https://yts.mx/languages",
    }
]
const footerLinks2: NavLink[]=[
    {
        id: 1,
        name: "EZTV",
        link: "https://eztv.li",
    },
    {
        id: 2,
        name: "YIFY Status",
        link: "https://yifystatus.com",
    },
    {
        id: 3,
        name: "YTS Proxies",
        link: "https://ytsproxies.com",
    },
    {
        id: 4,
        name: "YTS Proxies (TOR)",
        link: "http://ytsyifyupcmxftncrnqd4bmwxvhlibhdat74w6xnmn33njxts4eeaiqd.onion/",
    },
]

export default navLinks;
export {dropdownlist, footerLinks, footerLinks2}
